# Generated by Django 3.0.3 on 2020-02-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='highlight',
            field=models.BooleanField(default=False, verbose_name='Highlight'),
        ),
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Veröffentlicht'),
        ),
    ]
